version: '3.5'
services:
  app:
    container_name: ${VERSION:-0}app
    image: olaseni/python-django:dps-1.0
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-dps.settings.development}
      - DJANGO_SUPER_USER=${DJANGO_SUPER_USER:-admin}
      - DJANGO_SUPER_EMAIL=${DJANGO_SUPER_EMAIL:-admin@example.org}
      - DJANGO_SUPER_PASSWORD #a random one is generated if blank

    depends_on:
    - db
    ports:
    - "9000:9000"
    volumes:
    - ./django-context/src/:/src/

  db:
    container_name: ${VERSION:-0}db
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
    volumes:
    - pgdata:/var/lib/postgresql/data

  redis:
    container_name: ${VERSION:-0}redis
    image: redis:5.0-rc4-alpine

  adm:
    container_name: ${VERSION:-0}adm
    image: adminer
    ports:
    - "8090:8080"

volumes:
  pgdata: