# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: docker/compose:1.22.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Container & Run Tests
          command: |
            # the no-start/create step is enable `docker cp` to operate with established container ids
            # it's a work-around for the limitations of circleci "no bind mounts" issue
            docker-compose --log-level ERROR up --no-start
            docker cp ./django-context/src/ $(docker-compose --log-level ERROR ps -q web):/src/
            # docker-compose up --abort-on-container-exit --exit-code-from app
            make up