#!/bin/bash


CMD="make lint-and-test" # Command that runs your tests
protected_branch='master'

# Check if we actually have commits to push
commits=$(git log @{u}..)
if [[ -z "$commits" ]]; then
    exit 0
fi

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ "$current_branch" != "$protected_branch" ]]; then
    $CMD
    RESULT=$?
    if [ $RESULT -ne 0 ]; then 
        echo "Failed command: [ $CMD ]"
        exit 1
    fi
else
	echo "Can't push protected branch: ${protected_branch}"
	exit 1
fi
exit 0