# Generated by Django 2.1.4 on 2018-12-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
