# Generated by Django 2.1.4 on 2018-12-07 02:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0002_auto_20181207_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cause',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='primary_contact',
        ),
        migrations.AlterField(
            model_name='cause',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.TextField(help_text='Full description of the cause. This will be displayed to the user'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='cause',
            name='target_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promise',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='promise',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cause',
            name='contact',
            field=models.ForeignKey(default=0, help_text='Contact associated with the cause', on_delete=django.db.models.deletion.CASCADE, to='dps_main.Contact'),
            preserve_default=False,
        ),
    ]
