# Generated by Django 2.1.4 on 2018-12-07 02:29

from django.db import migrations, models
import dps_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0003_auto_20181207_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='expiration_date',
            field=models.DateTimeField(default=dps_main.models.tomorrow, help_text='Date for which this cause is no longer valid'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='target_amount',
            field=models.FloatField(default=0.0, help_text='Amount promised in NGN'),
        ),
    ]
