# Generated by Django 2.1.4 on 2018-12-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0004_auto_20181207_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='contact',
            field=models.ForeignKey(help_text='Contact associated with the cause', on_delete=django.db.models.deletion.CASCADE, to='dps_main.Contact', verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='target_amount',
            field=models.FloatField(default=0.0, help_text='Amount promised in NGN', verbose_name='Amount promised'),
        ),
    ]
