# Generated by Django 2.1.4 on 2018-12-07 02:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dps_main', '0005_auto_20181207_0235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promise',
            unique_together={('cause', 'user')},
        ),
    ]
