# Generated by Django 2.1.4 on 2018-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0006_auto_20181207_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
