# Generated by Django 2.1.4 on 2018-12-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0008_auto_20181207_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='illustration',
            field=models.ImageField(help_text='Images associated with the cause', upload_to='uploads/illustration'),
        ),
    ]
