# Generated by Django 2.1.4 on 2018-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0009_auto_20181207_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='illustration',
            field=models.ImageField(help_text='Images associated with the cause', upload_to='illustration/%Y/%m/%d/'),
        ),
    ]
