# Generated by Django 2.1.4 on 2018-12-07 07:48

from django.db import migrations, models
import dps_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0010_auto_20181207_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='expiration_date',
            field=models.DateField(default=dps_main.models.tomorrow, help_text='Date for which this cause is no longer valid'),
        ),
    ]
