# Generated by Django 2.1.4 on 2018-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0012_auto_20181207_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='target_amount',
            field=models.FloatField(default=0.0, help_text='Amount targeted in NGN', verbose_name='Amount targeted, NGN'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='amount',
            field=models.FloatField(help_text='Amount promised toward the associated cause, NGN', verbose_name='Amount promised, NGN'),
        ),
    ]
