# Generated by Django 2.1.4 on 2018-12-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0014_auto_20181208_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='contact',
            field=models.OneToOneField(help_text='Contact associated with the cause', on_delete=django.db.models.deletion.CASCADE, to='dps_main.Contact', verbose_name='Primary Contact'),
        ),
    ]
