# Generated by Django 2.1.4 on 2018-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_main', '0016_auto_20181212_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
